### ISSUE TITLE
Customize browsers

### ISSUE THREAD

**Issue by malaudha** [vivek9patel/vscode-css-compatibility#2]
Could it be possible to let the user choose the browsers? For instance, I'd really like to add IE to the scope.

**Comment by vivek9patel** [comment]
Yes, I will add configuration that user can change from settings.

**Comment by vivek9patel** [comment]
@malaudha the option to enable/disable browser type has been added with version [1.0.2](https://github.com/vivek9patel/vscode-css-compatibility/releases/tag/1.0.2). You can now go to your vscode settings, look for "CSS Compatibility" and enable any browser type you want to check compatibility for.

Please update your extension and let me know if you have any trouble, thanks for creating the issue : )

**Comment by malaudha** [comment]
Hello Patel, thanks for the fast addition! The option is working great in a `.css` file, however I don't see the popup appear in some parts of`.less` files.
For instance, the upper part (keyframes) shows the popup but the lower doesn't: 
```@keyframes left-appear {
  0% {
    transform: translateX(-10%);
    opacity: 0;
  }

  100% {
    transform: translateX(0%);
    opacity: 1;
  }
}

.inner {
/* what follows does not work */
  .zoom-container {
    overflow: hidden;
  }
}
```
I think the popup doesn't show with nested nodes because if you remove the `.inner` parent around `.zoom-container`, the popup behaves correctly. It might not be linked to this addition, let me know if you want me to open another issue.

**Comment by vivek9patel** [comment]
I'm aware of this bug. Right now I am parsing sass/scss/less files as CSS, that is why nested property is not working. I'm thinking of a solution for this. 
There is already an issue created for this: https://github.com/vivek9patel/vscode-css-compatibility/issues/3

**Comment by malaudha** [comment]
Ok great! Might be useful for the not so incompatible nested syntax for native CSS :) https://caniuse.com/?search=css%20nesting

**Comment by vivek9patel** [comment]
I see, however I am using [csstree](https://github.com/csstree/csstree) parser, which will not get every scss or less syntax. So I am thinking of adding scss/less parser for those file types, Which will be more appropriate.
